apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: keyvaultmaps.keyvault.turnoutt.com
spec:
  group: keyvault.turnoutt.com
  names:
    kind: KeyVaultMap
    listKind: KeyVaultMapList
    plural: keyvaultmaps
    singular: keyvaultmap
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: KeyVaultMap is the Schema for the keyvaultmaps API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: KeyVaultMapSpec defines the desired state of KeyVaultMap
          properties:
            credentials:
              description: KeyVaultCredentialsSpec defines the credentials to connect
                to a key vault instance. This is used if not using managed identity.
              properties:
                client-id:
                  type: string
                client-secret:
                  type: string
              required:
              - client-id
              - client-secret
              type: object
            mappings:
              items:
                description: KeyVaultSecretBindingSpec defines the desired state of
                  KeyVaultMap
                properties:
                  environment-variable-mapping:
                    type: string
                  secret-name:
                    type: string
                required:
                - environment-variable-mapping
                - secret-name
                type: object
              type: array
            tenant-id:
              type: string
            vault-name:
              type: string
          required:
          - credentials
          - mappings
          - tenant-id
          - vault-name
          type: object
        status:
          description: KeyVaultMapStatus defines the observed state of KeyVaultMap
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
