// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyVaultMap) DeepCopyInto(out *KeyVaultMap) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyVaultMap.
func (in *KeyVaultMap) DeepCopy() *KeyVaultMap {
	if in == nil {
		return nil
	}
	out := new(KeyVaultMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeyVaultMap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyVaultMapList) DeepCopyInto(out *KeyVaultMapList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeyVaultMap, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyVaultMapList.
func (in *KeyVaultMapList) DeepCopy() *KeyVaultMapList {
	if in == nil {
		return nil
	}
	out := new(KeyVaultMapList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeyVaultMapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyVaultMapSpec) DeepCopyInto(out *KeyVaultMapSpec) {
	*out = *in
	if in.Mappings != nil {
		in, out := &in.Mappings, &out.Mappings
		*out = make([]KeyVaultSecretBindingSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyVaultMapSpec.
func (in *KeyVaultMapSpec) DeepCopy() *KeyVaultMapSpec {
	if in == nil {
		return nil
	}
	out := new(KeyVaultMapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyVaultMapStatus) DeepCopyInto(out *KeyVaultMapStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyVaultMapStatus.
func (in *KeyVaultMapStatus) DeepCopy() *KeyVaultMapStatus {
	if in == nil {
		return nil
	}
	out := new(KeyVaultMapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyVaultSecretBindingSpec) DeepCopyInto(out *KeyVaultSecretBindingSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyVaultSecretBindingSpec.
func (in *KeyVaultSecretBindingSpec) DeepCopy() *KeyVaultSecretBindingSpec {
	if in == nil {
		return nil
	}
	out := new(KeyVaultSecretBindingSpec)
	in.DeepCopyInto(out)
	return out
}
